# Sample IDs that would be used for your sequence IDs
sample_ids: config/sample_ids.csv
sample_ids_col_name: "Process ID"

# path to raw reads
project_dir: "absolute/path/to/reads"

#delimeter for all output tables
delimiter: "\t"

# forward adapter
forward_adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA

# reverse adapter
reverse_adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

# fastp deduplication (True/False)
fastp_dedup: True

# plot dimensions (cm)
plot_height: 20
plot_width: 20
